"""Initial migration

Revision ID: 5f49deb04c31
Revises: 
Create Date: 2024-02-06 17:41:06.222410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f49deb04c31'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### dependencies ###
    op.execute("CREATE EXTENSION IF NOT EXISTS intarray")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('gb_id', sa.String(length=16), nullable=False),
    sa.Column('ISBN', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('language', sa.String(length=2), nullable=True),
    sa.Column('pub_date', sa.String(), nullable=True),
    sa.Column('categories', sa.String(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('banned', sa.Boolean(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('excluded_categories', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('books_users_associations',
    sa.Column('left_id', sa.Integer(), nullable=False),
    sa.Column('right_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['left_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('left_id', 'right_id')
    )
    op.create_table('user_api_keys',
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expire_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
INSERT INTO "users" ("name", "email", "username", "password", "banned", "permissions", "excluded_categories", "created_at")
VALUES ('Super User', 'super@user.com', 'superuser', '$2b$12$RkU7Zjy1b5RXdvJhRGxyHuXFMTpwKlD.E84Brsa25w9qugKj4RWwG', '0', '{
        "can_view_users": true,
         "can_add_users": true,
        "can_ban_users": true,
        "can_delete_users": true,
        "can_edit_user_profile": true,
        "can_edit_user_permissions": true,
        "super_user": true
}', '{}', timezone('utc', now()));
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_api_keys')
    op.drop_table('books_users_associations')
    op.drop_table('users')
    op.drop_table('books')
    # ### end Alembic commands ###
